[package]
name = "quantum-nn-steg-hardened"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
image = "0.24"
imageproc = "0.23"
rand = "0.8"
sha2 = "0.10"
crc32fast = "1.3"
bzip2 = "0.4"
indicatif = "0.17"
rustdct = "0.7"
rayon = "1.10"
